services:
  nginx:
    image: nginx:1.25-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    ports:
      - "9999:9999"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "40MB"

  app1: &app1
    #image: laurosantana/backend-rinha-2025:latest
    build:
      dockerfile: Dockerfile
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - SERVER_PORT=9090
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=postgres
      - MIGRATE=1
      - POOL_SIZE=5
      - CHANNEL_BUFFER=2000
      - CHANNEL_CONSUMER=2
    networks:
      - backend
      - payment-processor
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "100MB"

  app2:
    <<: *app1
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - SERVER_PORT=9091
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=postgres
      - POOL_SIZE=5
      - CHANNEL_BUFFER=2000
      - CHANNEL_CONSUMER=2
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "100MB"

  postgres:
    container_name: postgres
    image: postgres:16.3-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "110MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true